output_f = "{:+d}".format(52)
output_g = "{:+d}".format(-52)
output_h = "{: d}".format(52)
output_i = "{: d}".format(-52)

print("#기호와함께출력하기")
print(output_f)
print(output_g)
print(output_h)
print(output_i)
